# Generated by Django 3.1 on 2020-08-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_test_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/t1.png', upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='image',
        ),
    ]
