# Generated by Django 3.1 on 2020-08-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20200809_0130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModel',
        ),
    ]
